### PR TITLE
fix componentWillReceiveProps

### LINKED ISSUE #14: fix componentWillReceiveProps
Should be given nextProps, not newProps

https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops

### PR DESCRIPTION
**Pull request by ghost**
fixes #14

### CODE REVIEW

File: test.ts [hunk 1]
```diff
@@ -109,7 +109,7 @@ describe('Component', () => {
         const {parentScope, scope} = renderComponent(A)
         const spy = spyOn(scope.$ctrl, 'componentWillReceiveProps')
         parentScope.$apply(() => parentScope.a = 20)
-        expect(spy).toHaveBeenCalledWith({ a: 20 })
+        expect(spy).toHaveBeenCalledWith({ a: 20, b: 'foo' })
```
Comment (bcherny) [inline test.ts]: Can you also add a test that `props != this.props`?

**Review by bcherny — APPROVED** [review]
