### PR TITLE
fix shouldComponentUpdate

### LINKED ISSUE #8: shouldComponentUpdate does not work as expected
Expected: It should be called with `(nextProps, nextState)`, and inside the method `this.props` and `this.state` should refer to the current props and state.

Actual: It is called with `(nextProps, nextProps)`, and inside the method `this.props` refers to the same `nextProps`.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #8

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -14,33 +14,28 @@ abstract class NgComponent<Props, State> {
...
     const newProps = mapValues<{}, Props>(changes, 'currentValue')
 
-    if (!this.__isFirstRender) {
-      this.componentWillReceiveProps(newProps)
-    }
-
-    // store the new props
-    this.props = assign({}, this.props, newProps)
+    const props = assign({}, this.props, newProps)
+    const state = assign({}, this.state) // TODO: implement setState and test it with shouldComponentUpdate
```
Comment (bcherny) [inline index.ts]: Is this to prevent reference equality between `state` and `this.state` in `shouldComponentUpdate`? If so, we should add a test.

File: index.ts [hunk 2]
```diff
@@ -14,33 +14,28 @@ abstract class NgComponent<Props, State> {
...
 
     if (this.__isFirstRender) {
+      assign(this, { props, state })
       this.componentWillMount()
       this.render()
       this.__isFirstRender = false
+    } else {
+      this.componentWillReceiveProps(newProps)
+      if (!this.didPropsChange(newProps, oldProps)) return
+      const shouldUpdate = this.shouldComponentUpdate(props, state)
```
Comment (bcherny) [inline index.ts]: Can we add a test for state?

**Comment by bcherny** [comment]
Looks great. Let's add some tests and get this merged.

File: index.ts (hunk 1 above)
Comment (ghost) [reply index.ts]: no, i originally wanted to implement setState but there's quite a bit involved to it which I'll do in the future

**Comment by ghost** [comment]
if its ok, ill fix state later - implementing setState is a fair amount of work #15

**Review by bcherny — APPROVED** [review]
